version: "3"
services:
  api:
    container_name: "backend_vuttr"
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app/src 
    environment:
      - MONGO_URI=mongodb://mongo/vuttr
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    links:
      - mongo_api
    depends_on:
      - mongo_api
    command: npm start
  mongo_api:
    container_name: "mongo_vuttr"
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    
